<?php

namespace AppBundle\Repository;

/**
 * PriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriorityRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllOrderedByWeight()
    {
      return $this->createQueryBuilder('p')
        ->orderBy('p.weight', 'ASC')
        ->getQuery()
        ->getResult()
      ;
    }
}
