<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllSorted()
    {
      return $this->createQueryBuilder('t')
        ->addOrderBy('t.deadline', 'ASC')
        ->addOrderBy('t.priority', 'ASC')
        ->getQuery()
        ->getResult()
      ;
    }
}
